Feature: Support pinned messages
Wunderfitz/harbour-fernschreiber pull request #177
Opened 2020-11-18 14:12 UTC by Wunderfitz

This is the replacement for the ill-fated PR #175 which I completely messed up. It should include all the work and the additional changes which were proposed by @jgibbon. Moreover, unpinning messages is now supported as well. Happy testing!

2020-11-18 15:36 UTC, jgibbon requested changes
Still works fine for general usage, but there's an issue handling the unpin. 

I ran into the Telegram rate limit (that was a first!) while testing, so here it is from memory, a bit rough:
- Pin two messages, unpin one, the displayed pinned message does not update.
- (could be because of rate limit? but I did get the error only afterwards) At one point after pinning a message, the area was displayed but empty.

Other than that: Really nice feature!

2020-11-18 15:36 UTC, jgibbon commented on qml/components/MessageListViewItem.qml
>                          }
Perhaps you don't even need the Item at all…
```suggestion
                        InReplyToRow {
                            id: messageInReplyToRow
                            myUserId: page.myUserId
                            visible: true
                            inReplyToMessage: messageInReplyToLoader.inReplyToMessage
                            
                            MouseArea {
                                anchors.fill: parent
                                onClicked: {
                                    messageOverlayLoader.overlayMessage = messageInReplyToRow.inReplyToMessage;
                                    messageOverlayLoader.active = true;
                                }
                            }
                        }
```

2020-11-18 16:45 UTC, Wunderfitz commented
I also had the rate limiting (too many pins/unpins triggers it, yes...). But I couldn't reproduce the issue that the area is displayed empty. Strange... If you have any more concrete hint, please let me know. I'll check!

Concerning the Item - I also thought I won't need it. However, afterwards, it looked like that:

![image](https://user-images.githubusercontent.com/15228698/99560036-b496a600-29c5-11eb-92e1-4d69a671f900.png)

So for now, I'll keep it that way... ;)

2020-11-19 10:20 UTC, Wunderfitz commented
Thx, then let's merge it!

2020-11-19 10:20 UTC, merged