Limit message width in widescreen UI.
Wunderfitz/harbour-fernschreiber pull request #548
Opened 2023-12-04 15:33 UTC by mbarashkov

This was intended to be included in https://github.com/Wunderfitz/harbour-fernschreiber/pull/540, but this change didn't make it into PR.

It further improved chat UI on tablets (or wide screens as we call them now) by limiting message width to 75% of the screen.

2023-12-04 21:21 UTC, Wunderfitz commented
It actually made it into the PR, but I reverted that after the discussion in https://github.com/Wunderfitz/harbour-fernschreiber/pull/540#issuecomment-1837311941 I guess, we need to come to a common conclusion here and I thought we agreed to restore the old behavior...

2023-12-04 21:22 UTC, Wunderfitz requested changes
See my comment and the one in https://github.com/Wunderfitz/harbour-fernschreiber/pull/540#issuecomment-1837311941

2023-12-05 07:42 UTC, mbarashkov commented
Understood @Wunderfitz 
I will fix message aligning on tablets and update

2023-12-22 13:53 UTC, mbarashkov commented
@Wunderfitz 
PR updated, as per requested changes and tweaks.

2024-01-03 23:56 UTC, monich commented
Should this fix polls (which got squeezed too)

2024-01-04 12:01 UTC, mbarashkov commented
Will add poll fix as well

2024-01-04 12:42 UTC, mbarashkov commented
PR updated; polls now use full width of message.

2026-08-18 21:10 UTC, Wunderfitz commented
Did some additional tests with the current version and the Jolla 2 in widescreen. I have to admit that I like it as is, media sizes are limited and things have become even better with album support as it seems. In addition, I don't want to limit the message width in widescreen. Sorry, but closing for now.

2026-08-18 21:10 UTC, closed without merging